version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions   # also keeps actions/* up to date
    directory: "/"
    schedule:
      interval: weekly
